# Generated by Django 4.2.27 on 2025-12-16 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio_compra', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('meses', models.FloatField()),
                ('inversion_total', models.FloatField()),
                ('beneficio_bruto', models.FloatField()),
                ('beneficio_inversure', models.FloatField()),
                ('beneficio_neto_inversure', models.FloatField()),
                ('beneficio_participes', models.FloatField()),
                ('rentabilidad_total', models.FloatField()),
                ('rentabilidad_anualizada', models.FloatField()),
                ('cumple_roi', models.BooleanField()),
                ('precio_breakeven', models.FloatField()),
                ('colchon_seguridad', models.FloatField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
