# Generated by Django 4.2.27 on 2025-12-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('ref_catastral', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_propiedad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_compra_inmueble', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_venta_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('itp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notaria', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('registro', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gestoria_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('otros_gastos_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ibi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comunidad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('suministros', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('seguros', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('limpieza_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('limpieza_periodica', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reforma', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mobiliario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ocupas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('otros_puesta_marcha', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coste_comercializacion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coste_administracion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inmobiliaria', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plusvalia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gestoria_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('otros_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('val_idealista', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('val_fotocasa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('val_casafari', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('val_registradores', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('val_tasacion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('meses_operacion', models.PositiveIntegerField(blank=True, null=True)),
                ('financiacion_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inversion_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('beneficio_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('roi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
