# Generated by Django 4.2.27 on 2025-12-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='comunidad',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='coste_administracion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='coste_comercializacion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='financiacion_pct',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='gestoria_compra',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='gestoria_venta',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='ibi',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='inmobiliaria',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='inversion_total',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='limpieza_inicial',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='limpieza_periodica',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='meses_operacion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='mobiliario',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='ocupas',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='otros_puesta_marcha',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='otros_venta',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='plusvalia',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='reforma',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='seguros',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='suministros',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='val_casafari',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='val_fotocasa',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='val_idealista',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='val_registradores',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='val_tasacion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='valor_medio',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='beneficio_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='gastos_administracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='gastos_comercializacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='beneficio_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='itp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='notaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='otros_gastos_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='precio_compra_inmueble',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='precio_propiedad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='precio_venta_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='registro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='roi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='valor_referencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
