# Generated by Django 4.2.27 on 2026-01-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estudiosnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiosnapshot',
            name='codigo_version',
            field=models.CharField(default='EST-LEGACY', help_text='Código legible de versión del estudio (ej: EST-2026-001-v1)', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiosnapshot',
            name='es_convertible',
            field=models.BooleanField(default=False, help_text='Indica si este snapshot puede convertirse en proyecto'),
        ),
        migrations.AddField(
            model_name='estudiosnapshot',
            name='estado_estudio',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('en_estudio', 'En estudio'), ('denegado', 'Denegado')], default='borrador', help_text='Estado del estudio en el momento de generar el snapshot', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiosnapshot',
            name='fecha_decision_comite',
            field=models.DateTimeField(blank=True, help_text='Fecha de la decisión del comité (si aplica)', null=True),
        ),
        migrations.AlterField(
            model_name='estudiosnapshot',
            name='datos',
            field=models.JSONField(help_text='Datos completos congelados del estudio (comité, inversor, económico)'),
        ),
        migrations.AlterField(
            model_name='estudiosnapshot',
            name='version_simulador',
            field=models.CharField(default='v1', help_text='Versión del simulador con la que se generó el snapshot', max_length=20),
        ),
    ]
