# Generated by Django 4.2.27 on 2025-12-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_proyecto_comunidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='comunidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ibi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='inmobiliaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='limpieza_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='limpieza_periodica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='mobiliario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ocupas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='otros_puesta_marcha',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='plusvalia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='reforma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='seguros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='suministros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
