# Generated by Django 4.2.27 on 2026-01-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estudiosnapshot_codigo_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='guardado',
            field=models.BooleanField(default=False, help_text='Marca si el estudio está finalizado/guardado (True) o es borrador (False)'),
        ),
    ]
