# Generated by Django 4.2.27 on 2026-01-09 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estudio_guardado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='Si True, el estudio está congelado (no editable) porque ha sido convertido a proyecto'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='bloqueado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora en que el estudio se bloqueó (conversión a proyecto)', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='convertido_desde_estudio',
            field=models.BooleanField(default=False, help_text='Marca si el proyecto fue generado desde un estudio (True) o creado manualmente'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='origen_estudio',
            field=models.ForeignKey(blank=True, help_text='Estudio del que procede este proyecto (fase de análisis previa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='core.estudio'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='origen_snapshot',
            field=models.ForeignKey(blank=True, help_text='Snapshot final del estudio usado para convertir a proyecto (estado congelado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='core.estudiosnapshot'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='snapshot_datos',
            field=models.JSONField(blank=True, help_text='Copia inmutable de los datos del snapshot en el momento de conversión', null=True),
        ),
    ]
