# Generated by Django 4.2.27 on 2025-12-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_proyecto_meses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='gastos_administracion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='gastos_comercializacion',
        ),
    ]
