# Generated by Django 4.2.27 on 2025-12-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_proyecto_beneficio_bruto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_invertido', models.DecimalField(decimal_places=2, help_text='Cantidad aportada por el cliente al proyecto', max_digits=12)),
                ('porcentaje_participacion', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de participación sobre el total invertido', max_digits=6, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='core.cliente')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='core.proyecto')),
            ],
        ),
    ]
