# Generated by Django 4.2.27 on 2025-12-24 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_participacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cuota_abonada',
            field=models.BooleanField(default=False, help_text='Indica si el cliente ha abonado la cuota'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_postal',
            field=models.TextField(blank=True, help_text='Dirección postal completa del cliente', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_introduccion',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de alta del cliente en el sistema'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='presente_en_comunidad',
            field=models.BooleanField(default=False, help_text='Indica si el cliente está presente en la comunidad'),
        ),
    ]
