# Generated by Django 4.2.27 on 2025-12-24 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cliente_cuota_abonada_cliente_direccion_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificativo de la simulación', max_length=255)),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha de creación de la simulación')),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='Precio estimado de compra del inmueble', max_digits=12)),
                ('precio_venta_estimado', models.DecimalField(decimal_places=2, help_text='Precio estimado de venta del inmueble', max_digits=12)),
                ('gastos_estimados', models.DecimalField(decimal_places=2, default=0, help_text='Gastos estimados globales (simplificados)', max_digits=12)),
                ('beneficio_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Beneficio estimado de la simulación', max_digits=12, null=True)),
                ('roi_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='ROI estimado (%)', max_digits=6, null=True)),
                ('viable', models.BooleanField(default=False, help_text='Indica si la simulación supera los criterios de viabilidad')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
