# Generated by Django 4.2.27 on 2025-12-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_simulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='simulacion_origen',
            field=models.ForeignKey(blank=True, help_text='Simulación de la que procede este proyecto (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_generados', to='core.simulacion'),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='convertida',
            field=models.BooleanField(default=False, help_text='Indica si la simulación ya ha sido convertida en proyecto'),
        ),
    ]
