# Generated by Django 4.2.27 on 2025-12-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_simulacion_beneficio_simulacion_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección del inmueble del proyecto', max_length=255, null=True),
        ),
    ]
