# Generated by Django 4.2.27 on 2025-12-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_proyecto_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitud del inmueble (geolocalización)', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='lon',
            field=models.FloatField(blank=True, help_text='Longitud del inmueble (geolocalización)', null=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitud del inmueble (geolocalización)', null=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='lon',
            field=models.FloatField(blank=True, help_text='Longitud del inmueble (geolocalización)', null=True),
        ),
    ]
