# Generated by Django 4.2.27 on 2025-12-31 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_documentoproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoEconomicoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('operacion', 'Operación'), ('ingreso', 'Ingreso'), ('comercializacion', 'Comercialización')], max_length=20)),
                ('subtipo', models.CharField(blank=True, max_length=50, null=True)),
                ('concepto', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.documentoproyecto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_economicos', to='core.proyecto')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DatosEconomicosProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_operativo', models.CharField(choices=[('captacion', 'Captación'), ('comercializacion', 'Comercialización'), ('cierre', 'Cierre'), ('vendido', 'Vendido'), ('cancelado', 'Cancelado')], default='captacion', max_length=20)),
                ('fecha_estado', models.DateField(blank=True, null=True)),
                ('observaciones_estado', models.TextField(blank=True, null=True)),
                ('precio_compra_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_compra_real', models.DateField(blank=True, null=True)),
                ('tipo_adquisicion', models.CharField(blank=True, max_length=20, null=True)),
                ('impuesto_tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('impuesto_porcentaje_real', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('impuesto_importe_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notaria_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('registro_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gestoria_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('otros_gastos_adquisicion_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_venta_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_venta_real', models.DateField(blank=True, null=True)),
                ('gastos_venta_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plusvalia_municipal_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('honorarios_agencia_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tipo_comision_gestion', models.CharField(choices=[('porcentaje_beneficio', 'Porcentaje sobre beneficio'), ('porcentaje_ingresos', 'Porcentaje sobre ingresos'), ('importe_fijo', 'Importe fijo')], default='porcentaje_beneficio', max_length=30)),
                ('valor_comision_gestion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_economicos', to='core.proyecto')),
            ],
        ),
    ]
