# Generated by Django 4.2.27 on 2025-12-31 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_movimientoeconomicoproyecto_datoseconomicosproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoseconomicosproyecto',
            name='porcentaje_administracion',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Porcentaje de administración sobre el beneficio bruto', max_digits=5),
        ),
        migrations.AddField(
            model_name='datoseconomicosproyecto',
            name='porcentaje_comercializacion',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Porcentaje de comercialización sobre el beneficio bruto', max_digits=5),
        ),
        migrations.AlterField(
            model_name='gastoproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_proyecto', to='core.proyecto'),
        ),
    ]
