# Generated by Django 4.2.27 on 2026-01-02 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_gastosproyectoestimacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Concepto del gasto o ingreso presupuestado', max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('importe_previsto', models.DecimalField(decimal_places=2, help_text='Importe estimado del concepto', max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='core.proyecto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso')], max_length=10)),
                ('concepto', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documento', models.FileField(blank=True, null=True, upload_to='movimientos_proyecto/%Y/%m/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.proyecto')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
